version: '2'

networks:
  swarm:
  public:

services:

  # ngnix reverse proxy
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - public
      - swarm
    depends_on:
      - hapi
      - falcon
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/var/www:ro
      - ./logs/nginx:/var/logs
      
  # ngnix reverse proxy
  hapi:
    container_name: hapi
    build: ./hapi
    networks:
      - swarm
      
  falcon:
    container_name: falcon
    build: ./falcon
    networks:
      - swarm